management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: h2
    password: h2
  h2:
    console:
      enabled: true  # :8080/h2-console